// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustVolume(arg1:number):Promise<void>;

export function SetMute(arg1:boolean):Promise<void>;

export function SetPlaybackEnabled(arg1:boolean):Promise<void>;
