// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustVolume(arg1) {
  return window['go']['main']['App']['AdjustVolume'](arg1);
}

export function SetMute(arg1) {
  return window['go']['main']['App']['SetMute'](arg1);
}

export function SetPlaybackEnabled(arg1) {
  return window['go']['main']['App']['SetPlaybackEnabled'](arg1);
}
